### linear vs logistic regression
- linear regression predicts continuous outcome
	- infinite possibilities i.e. negative -∞ - ∞
- logistic regression predicts discrete outcome
	- i.e. binary
	- logistic funciton -> sigmoid funciton

---
### intro to neural networks
- neural networks - separate data
- classification - create algo to find line that best* separate data. (Least error)
	- linear equations w1x1 + w2x2 + b = 0 or Wx + b = 0
		- W = (w1, w2) <- weights
		- x = (x1, x2) <- inputs
		- b <- bias
		- y <- label (0, 1)
		- y^ <- prediction
	- goal is to have y == y^
- perceptron - linear function + step function
	- linear function - node (inputs) + edges (weights)
	- step function - return binary
- **perceptron trick**
	- for a misclassified point, move the line closer
	- take the point and bias multiple by the *learning rate* add/subtract from the line
- **error function**
    - how far we are from the solution or distance i.e. tell robot to get cake.
    - how bad is each point classified
        1. Look around
        2. Take the step that gets you closer to the objective
        3. Repeat
        - needs to be continuous not discrete
	- step -> sigmoid function $\hat{y} = σ(Wx+b)$ aka prediction
    - if **correctly** classified - small number
    - if **incorrectly** classified - large number 
    - $$Error(W) = -\frac{1}{m} \sum\limits_{i=1}^{m} y_i \log(\hat{y}_i) - (1-y_i) \log(1-\hat{y}_i)$$
- **softmax function** - multi-class classification, exponent
- **one-hot encoding** - a way to label input/output data as vectors instead of actual words i.e. “dog”, “cat”; processing data
	- [One-hot Encoding explained - YouTube](https://www.youtube.com/watch?v=v_4KWmkwmsU)
- **probabiliy function** - where the points in the blue region are more likely to be blue and the points in the red region are more likely to be red.
- **maximum likelihood** - maximize probability
- **cross-entropy** - sum of negative of logarithms of probabilities. ~Relationship between probabilities and error functions~ or ~how likely are the events happen based on the probabilities~ or ~how similar are the vectors~
	- smaller the cross entropy the better
	- goal: minimize cross entropy
- **logistic regression**
	- take data
	- pick a random model
	- calculate error
	- minimize error -> get better model
	- repeat
- **gradient descent** - misclassified points tell the line to come close vs. correctly classified points tell the line to go farther away
	- small gradient -> change coordinates by a little bit vice versa
- **logistic regression/ gradient descent algorithm**
    - [DL 32 Gradient Descent Algorithm Fix - YouTube](https://youtu.be/snxmBgi_GeU)
- **non-linear models** 
    - combine linear models, calculate the probability for each, sum them all up and apply the sigmoid function.
    - linear combinations * weight + bias
- **neural network architecture** - combine perceptrons 
	- **multi-class classification**
- **feedforward** - turn input into output. Linear combinations
- **backpropagation**
	- feedforward
	- compare output of model w/ desired output
	- calculate error
	- run feedforward backwards (backpropagation) updating weights to minimize error
	- keep going until model is good

### Perceptron Trick

In [ ]:
x1 = 4
x2 = 5

def line(x1, x2):
    return 3*x1 + 4*x2 - 10

def line2(x1, x2):
    return 2.6*x1 + 3.5*x2 - 10.1

def line3(x1, x2, bias=1, alpha=0.1):
    return (3 - x1 * alpha) *x1 + (4 - x2 * alpha)*x2 - (10 - bias * alpha)

print(line(x1, x2))
print(line2(x1, x2))
print(line3(x1, x2))

In [ ]:
def line4(x1, x2, bias=1, alpha=0.1):
    return (3 + x1 * alpha) *x1 + (4 + x2 * alpha)*x2 - (10 + bias * alpha)

x1, x2 = 1, 1
print(line(x1, x2))
print(line4(x1, x2))

In [ ]:
for i in range(1, 11):
    print(line4(x1, x2, alpha+i))

In [ ]:
y = 
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
W = [[0.37454012]
 [0.95071431]]
[[0.37454012]
 [0.95071431]]
[[0.37454012]
 [0.95071431]]
[[0.37454012]
 [0.95071431]]
[[0.37454012]
 [0.95071431]]
[[0.37454012]
 [0.95071431]]
[[0.37454012]
 [0.95071431]]
[[0.37454012]
 [0.95071431]]
[[0.37454012]
 [0.95071431]]
[[0.37454012]
 [0.95071431]]
[[0.37454012]
 [0.95071431]]
[[0.37454012]
 [0.95071431]]
[[0.37454012]
 [0.95071431]]
[[0.37454012]
 [0.95071431]]
[[0.37454012]
 [0.95071431]]
[[0.37454012]
 [0.95071431]]
[[0.37454012]
 [0.95071431]]
[[0.37454012]
 [0.95071431]]
[[0.37454012]
 [0.95071431]]
[[0.37454012]
 [0.95071431]]
[[0.37454012]
 [0.95071431]]
[[0.37454012]
 [0.95071431]]
[[0.37454012]
 [0.95071431]]
[[0.37454012]
 [0.95071431]]
[[0.37454012]
 [0.95071431]]

b = 1.731993941811405
1.731993941811405
1.731993941811405
1.731993941811405
1.731993941811405
1.731993941811405
1.731993941811405
1.731993941811405
1.731993941811405
1.731993941811405

In [ ]:
import numpy as np
# Setting the random seed, feel free to change it and see different solutions.
np.random.seed(42)

'''
Recall that the perceptron step works as follows. 
For a point with coordinates (p,q), label y, and prediction given by the equation y^ = step(w1x1 + w2x2 + b) or Wx+b

If the point is correctly classified, do nothing. 
If the point is classified positive, but it has a negative label, change w -> w - αx
If the point is classified negative, but it has a positive label, change w -> w + αx
'''

def stepFunction(t):
    if t >= 0:
        return 1
    return 0

def prediction(X, W, b):
    return stepFunction((np.matmul(X,W)+b)[0])

# Perceptron trick - separate data
# The function should receive as inputs the data X, the labels y,
# the weights W (as an array), and the bias b,
# update the weights and bias W, b, according to the perceptron algorithm,
# and return W and b.
def perceptronStep(X, y, W, b, learn_rate = 0.01):
    for i in range(len(X)):
        y_hat = prediction(X[i], W, b)
        if y[i]-y_hat == 1:
            for j in range(len(X[i])):
                W[j] += learn_rate * X[i][j]
            b += learn_rate
        elif y[i]-y_hat == -1:
            for j in range(len(X[i])):
                W[j] -= learn_rate * X[i][j]
            b -= learn_rate
    return W, b
    
# This function runs the perceptron algorithm repeatedly on the dataset,
# and returns a few of the boundary lines obtained in the iterations,
# for plotting purposes.
# Feel free to play with the learning rate and the num_epochs,
# and see your results plotted below.
def trainPerceptronAlgorithm(X, y, learn_rate = 0.01, num_epochs = 25):
    x_min, x_max = min(X.T[0]), max(X.T[0])
    y_min, y_max = min(X.T[1]), max(X.T[1])
    W = np.array(np.random.rand(2,1))
    b = np.random.rand(1)[0] + x_max
    # These are the solution lines that get plotted below.
    boundary_lines = []
    for i in range(num_epochs):
        # In each epoch, we apply the perceptron step.
        W, b = perceptronStep(X, y, W, b, learn_rate)
        boundary_lines.append((-W[0]/W[1], -b/W[1]))
    return boundary_lines


### Discrete vs Continuous

In [ ]:
import math

def sigmoid(x):
    return 1 / (1 + math.exp(-x))

def prediction(x):
    return sigmoid(4 * x[0] + 5 * x[1] - 9)

inputs = [(1,1), (2,4), (5,-5), (-4,5)]
for input in inputs:
    print(prediction(input))

### Numpy Practice

In [ ]:
import numpy as np

# http://ml-cheatsheet.readthedocs.io/en/latest/linear_algebra.html#scalar-operations

In [ ]:
### neural network

learning_rate = 0.1 # alpha
weight = 0.5
input = 2
goal_pred = 0.8

for _ in range(20):
    pred = input * weight
    error = (pred - goal_pred) ** 2
    derivative = pred - goal_pred # gradient descent
    weight -= learning_rate * derivative
    
    print("Error", str(error), "Prediction", str(pred))

### Neural Network Architecture

In [ ]:
def prediction(w1, w2, b):
    return w1*0.4 + w2*0.6 + b

print(sigmoid(prediction(2,6,-2)))
print(sigmoid(prediction(3,5,-2.2)))
print(sigmoid(prediction(5,4,-3)))